version: "3.9"

services:
    django:
        build: .
        container_name: django
        command: >
          sh -c "python manage.py makemigrations && 
          python manage.py migrate 
          && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A mailing worker -l INFO
        volumes:
            - .:/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=mailing
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"

volumes:
    pgdata: